javac Beats.java
javac BeatsDialog.java
javac BinauralBeats.java
javac BinauralBeatsDialog.java
javac ComplexSignal.java
javac FreqDialog.java
javac GuiWindow.java
javac JSignalGenerator.java
javac PlayerMono.java
javac PlayerStereo.java
javac Signal.java
javac Sinusoid.java